### ISSUE TITLE
cos function in your paper while sin in your implementation

### ISSUE THREAD

**Issue by alphadl** [loshchil/SGDR#2]
See the title, Eq. (5) in your paper employed cosine function while using sin in your code: https://github.com/loshchil/SGDR/blob/master/SGDR_WRNs.py#L311

**Comment by loshchil** [comment]
It is sin(t0 + t) which is equivalent to cos(t) for t0=pi/2 used in the code. Given that t0 was selected to be constant, we simplified it to cos(t) in the paper.

**Comment by alphadl** [comment]
Thanks for your prompt reply~ I find that your paper has been implemented in PyTorch [optim.lr_scheduler.CosineAnnealingLR](https://pytorch.org/docs/stable/_modules/torch/optim/lr_scheduler.html#CosineAnnealingLR)

**Comment by loshchil** [comment]
I am aware of it. Thanks for your interest.
