### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by atztao** [loshchil/SGDR#3]
first form you paper used wrn model is 28-10 so the n should set to 4 but in this code the n is 5,so this just a misstake?or you paper result used?

**Comment by ztao1991** [comment]
also in the original  modle no bias but you set.in the test erro image i don't think you method make the test erro completely smooth but you did!so i doubt whether the foundation of this paper is correct.

**Comment by loshchil** [comment]
The default input parameters of main() (e.g., n=5, k=1) are set based on scenario index and in all cases n=4 (e.g., n=4, k=20), see the code.

**Comment by atztao** [comment]
oh,i see,thank you,why in your paper not used dropout maybe the result is better.
